"""The dojo-results block: visual solved markers and sibling links, rendered
into docs/problems/README.md."""

import json
from pathlib import Path

from mu.dojo import readme
from mu.dojo.sessions import SessionMeta


def _sess(pid, outcome):
    return SessionMeta(path=Path('/tmp/x'), outcome=outcome, goal='g',
                       session_id=pid, project_dir=f'/r/dojo/{pid}', model='m',
                       repair_iters=0, degeneration_refusals=0)


def _catalog(tmp_path, ids):
    p = tmp_path / 'problems-catalog.json'
    p.write_text(json.dumps({'problems': [{'id': i} for i in ids]}))
    return p


def test_visual_markers_and_sibling_links(tmp_path):
    cat = _catalog(tmp_path, ['p1-helloworld', 'p4-fibonacci', 'p9-vue-todo'])
    block = readme.render_block(
        [_sess('p1-helloworld', 'success'), _sess('p4-fibonacci', 'stalled')],
        catalog=cat)
    # passed -> ✅ PASS ; failed -> ❌ ; in catalog but not run -> ➖
    assert '| [p1-helloworld](p1-helloworld.md) | ✅ | PASS |' in block
    assert '| [p4-fibonacci](p4-fibonacci.md) | ❌ | STALLED |' in block
    assert '| [p9-vue-todo](p9-vue-todo.md) | ➖ | — (not run) |' in block
    # sibling links, not docs/problems/ (the file lives in docs/problems/)
    assert 'docs/problems/' not in block
    # full catalog is listed, in numeric order
    assert block.index('p1-') < block.index('p4-') < block.index('p9-')


def test_refresh_replaces_only_between_markers(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _catalog(tmp_path, ['p1-helloworld'])
    target = tmp_path / 'docs' / 'problems' / 'README.md'
    target.parent.mkdir(parents=True)
    target.write_text(
        "# Problems\n\nintro\n\n"
        "<!-- DOJO-RESULTS:START (auto-generated by mu.dojo — do not edit by hand) -->\n"
        "old\n<!-- DOJO-RESULTS:END -->\n\nfooter\n")
    readme.refresh([_sess('p1-helloworld', 'success')], 1, target=target)
    out = target.read_text()
    assert 'intro' in out and 'footer' in out          # surround untouched
    assert '✅' in out and 'old' not in out             # block replaced
