"""Rewrite README's auto-generated dojo results block. (Port of practice.sh's
``_refresh_readme_results`` awk.)

The front door must always show the LAST round's measured per-problem result, so
this *overwrites* the marked region (never accumulates). The curated table and
challenges elsewhere in README are left untouched.
"""

import json
import os
import re
from pathlib import Path

from .env import iso_now
from .sessions import SessionMeta

_START = '<!-- DOJO-RESULTS:START'
_END = '<!-- DOJO-RESULTS:END -->'
_HEADER = '<!-- DOJO-RESULTS:START (auto-generated by mu.dojo — do not edit by hand) -->'


def _catalog_ids(root: Path) -> list[str]:
    """All problem ids from problems-catalog.json (empty list if unreadable),
    so the table always lists the full set — not only the problems that
    happened to run in the last round."""
    try:
        cat = json.loads((root / 'problems-catalog.json').read_text())
        return [p['id'] for p in cat.get('problems', [])]
    except (OSError, json.JSONDecodeError, KeyError, TypeError):
        return []


def _problem_index(pid: str) -> int:
    """Numeric order for sorting p1..p10 (not the string order that puts p10
    before p2). 'p7-flask' -> 7; non-conforming ids sort last."""
    m = re.match(r'p(\d+)', pid)
    return int(m.group(1)) if m else 9999


def _result(sessions: list[SessionMeta]) -> str:
    """One cell for a problem. A problem (e.g. p10 in architect mode) can spawn
    several sessions — collapse them, worst outcome wins: PASS only if all
    succeeded, else the uppercased failing outcome."""
    if all(s.passed for s in sessions):
        return 'PASS'
    bad = next(s.outcome for s in sessions if not s.passed)
    return bad.upper()


def render_block(round_sessions: list[SessionMeta],
                 root: Path = Path('.')) -> str:
    """The replacement block (markers included) for this round's sessions.

    One row per catalog problem — each linked to its page in docs/ — with
    the measured result of the last round, or '—' for problems the round
    didn't reach (e.g. toolchain not installed, round terminated early).
    """
    by_pid: dict[str, list[SessionMeta]] = {}
    for s in round_sessions:
        by_pid.setdefault(s.problem_id, []).append(s)

    pids = _catalog_ids(root) or sorted(by_pid, key=_problem_index)
    # A round can surface a session for a problem that left the catalog —
    # append rather than drop, so no result is silently hidden.
    pids += [p for p in sorted(by_pid, key=_problem_index) if p not in pids]

    stamp = iso_now()
    model = os.environ.get('MU_AGENT_MODEL') or 'recommended'
    rows = [
        f"| [{pid}](docs/{pid}.md) | "
        f"{_result(by_pid[pid]) if pid in by_pid else '— (not run)'} |"
        for pid in pids
    ]
    return '\n'.join([
        _HEADER,
        f"_Last round: {stamp} · model: {model}_",
        '',
        '| Problem | Solved in last round |',
        '|---|---|',
        *rows,
        _END,
    ])


def refresh(round_sessions: list[SessionMeta], round_num: int,
            readme: Path = Path('README.md')) -> None:
    """Replace the DOJO-RESULTS block in README with this round's results.
    No-ops (like the awk) when README or the block is absent, or the round had
    no sessions."""
    if not readme.is_file() or not round_sessions:
        return
    text = readme.read_text(encoding='utf-8')
    if _START not in text or _END not in text:
        return
    block = render_block(round_sessions, root=readme.resolve().parent)
    new = re.sub(re.escape(_START) + r'.*?' + re.escape(_END), block, text,
                 count=1, flags=re.DOTALL)
    readme.write_text(new, encoding='utf-8')
    print(f"Updated README.md DOJO-RESULTS block (round {round_num}).")
