"""Rewrite README's auto-generated dojo results block. (Port of practice.sh's
``_refresh_readme_results`` awk.)

The front door must always show the LAST round's measured per-problem result, so
this *overwrites* the marked region (never accumulates). The curated table and
challenges elsewhere in README are left untouched.
"""

import os
import re
from datetime import datetime
from pathlib import Path

from .sessions import SessionMeta

_START = '<!-- DOJO-RESULTS:START'
_END = '<!-- DOJO-RESULTS:END -->'
_HEADER = '<!-- DOJO-RESULTS:START (auto-generated by mu.dojo — do not edit by hand) -->'


def _problem_index(pid: str) -> int:
    """Numeric order for sorting p1..p10 (not the string order that puts p10
    before p2). 'p7-flask' -> 7; non-conforming ids sort last."""
    m = re.match(r'p(\d+)', pid)
    return int(m.group(1)) if m else 9999


def _result(sessions: list[SessionMeta]) -> str:
    """One cell for a problem. A problem (e.g. p10 in architect mode) can spawn
    several sessions — collapse them, worst outcome wins: PASS only if all
    succeeded, else the uppercased failing outcome."""
    if all(s.passed for s in sessions):
        return 'PASS'
    bad = next(s.outcome for s in sessions if not s.passed)
    return bad.upper()


def render_block(round_sessions: list[SessionMeta]) -> str:
    """The replacement block (markers included) for this round's sessions."""
    by_pid: dict[str, list[SessionMeta]] = {}
    for s in round_sessions:
        by_pid.setdefault(s.problem_id, []).append(s)

    stamp = datetime.now().astimezone().isoformat(timespec='seconds')
    model = os.environ.get('MU_AGENT_MODEL') or 'recommended'
    rows = [f"| {pid} | {_result(by_pid[pid])} |"
            for pid in sorted(by_pid, key=_problem_index)]
    return '\n'.join([
        _HEADER,
        f"_Last round: {stamp} · model: {model}_",
        '',
        '| Problem | Result |',
        '|---|---|',
        *rows,
        _END,
    ])


def refresh(round_sessions: list[SessionMeta], round_num: int,
            readme: Path = Path('README.md')) -> None:
    """Replace the DOJO-RESULTS block in README with this round's results.
    No-ops (like the awk) when README or the block is absent, or the round had
    no sessions."""
    if not readme.is_file() or not round_sessions:
        return
    text = readme.read_text(encoding='utf-8')
    if _START not in text or _END not in text:
        return
    block = render_block(round_sessions)
    new = re.sub(re.escape(_START) + r'.*?' + re.escape(_END), block, text,
                 count=1, flags=re.DOTALL)
    readme.write_text(new, encoding='utf-8')
    print(f"Updated README.md DOJO-RESULTS block (round {round_num}).")
