"""Rewrite the auto-generated dojo results block in docs/problems/README.md.

The problem index must always show the LAST round's measured per-problem result,
so this *overwrites* the marked region (never accumulates). Everything outside
the markers — the intro, legend, and links — is left untouched.
"""

import json
import os
import re
from pathlib import Path

from .env import iso_now
from .sessions import SessionMeta

_START = '<!-- DOJO-RESULTS:START'
_END = '<!-- DOJO-RESULTS:END -->'
_HEADER = '<!-- DOJO-RESULTS:START (auto-generated by mu.dojo — do not edit by hand) -->'

# The problem index lives beside the per-problem pages; its links are siblings.
_TARGET = Path('docs/problems/README.md')
_CATALOG = Path('problems-catalog.json')


def _catalog_ids(catalog: Path = _CATALOG) -> list[str]:
    """All problem ids from problems-catalog.json (empty if unreadable), so the
    table always lists the full set — not only the problems that ran this round."""
    try:
        cat = json.loads(catalog.read_text())
        return [p['id'] for p in cat.get('problems', [])]
    except (OSError, json.JSONDecodeError, KeyError, TypeError):
        return []


def _problem_index(pid: str) -> int:
    """Numeric order for sorting p1..p10 (not string order, which puts p10 before
    p2). 'p7-flask' -> 7; non-conforming ids sort last."""
    m = re.match(r'p(\d+)', pid)
    return int(m.group(1)) if m else 9999


def _cell(sessions: list[SessionMeta]) -> tuple[str, str]:
    """(visual, outcome) for one problem. A problem can spawn several sessions
    (e.g. p10 in architect mode) — collapse them, worst outcome wins: solved only
    if all passed, else the uppercased failing outcome."""
    if all(s.passed for s in sessions):
        return '✅', 'PASS'
    bad = next(s.outcome for s in sessions if not s.passed)
    return '❌', bad.upper()


def render_block(round_sessions: list[SessionMeta],
                 catalog: Path = _CATALOG) -> str:
    """The replacement block (markers included) for this round's sessions.

    One row per catalog problem — linked to its sibling page — with a visual
    solved marker (✅ / ❌ / ➖ not run) and the measured outcome.
    """
    by_pid: dict[str, list[SessionMeta]] = {}
    for s in round_sessions:
        by_pid.setdefault(s.problem_id, []).append(s)

    pids = _catalog_ids(catalog) or sorted(by_pid, key=_problem_index)
    # A round can surface a session for a problem that left the catalog —
    # append rather than drop, so no result is silently hidden.
    pids += [p for p in sorted(by_pid, key=_problem_index) if p not in pids]

    rows = []
    for pid in pids:
        if pid in by_pid:
            visual, outcome = _cell(by_pid[pid])
        else:
            visual, outcome = '➖', '— (not run)'
        rows.append(f"| [{pid}]({pid}.md) | {visual} | {outcome} |")

    stamp = iso_now()
    model = os.environ.get('MU_AGENT_MODEL') or 'recommended'
    return '\n'.join([
        _HEADER,
        f"_Last round: {stamp} · model: {model}_",
        '',
        '| Problem | Solved? | Last outcome |',
        '|---|:---:|---|',
        *rows,
        _END,
    ])


def refresh(round_sessions: list[SessionMeta], round_num: int,
            target: Path = _TARGET) -> None:
    """Replace the DOJO-RESULTS block in the problem index with this round's
    results. No-ops when the target or the block is absent, or the round had no
    sessions."""
    if not target.is_file() or not round_sessions:
        return
    text = target.read_text(encoding='utf-8')
    if _START not in text or _END not in text:
        return
    block = render_block(round_sessions)
    new = re.sub(re.escape(_START) + r'.*?' + re.escape(_END), block, text,
                 count=1, flags=re.DOTALL)
    target.write_text(new, encoding='utf-8')
    print(f"Updated {target} DOJO-RESULTS block (round {round_num}).")
