#!/usr/bin/env bash
# setup-host.sh — Tune mu's local model to this machine's GPU. One GPU-detection
# pass picks a profile, then writes ~/.zshrc.mu (machine-local, outside the repo):
#   • MU_AGENT_MODEL — the model mu talks to in LM Studio. Pinned on *every* host:
#     without it mu auto-selects the first /v1/models entry, which can be a model
#     too large to load. The 7B on a capable card, the snappier 3B otherwise.
#   • MU_NUM_CTX — the KV-cache context the card can hold. Written only when it
#     beats mu's own 6000 default (e.g. 12288 on a ≥6 GB discrete NVIDIA card).
#
# This assumes LM Studio is already serving the chosen Qwen2.5-Coder model on
# http://localhost:1234; it tunes mu's env, it does not download models.
#
# ~/.zshrc.mu is sourced by your shell rc (the dotfiles .zshrc does this); a
# standalone user must add this line to ~/.zshrc / ~/.bashrc themselves:
#     [ -r "$HOME/.zshrc.mu" ] && source "$HOME/.zshrc.mu"
#
# NOTE: the model-selection thresholds below (≥6000 MiB → 7B) are intentionally
# duplicated in the dotfiles repo's scripts/setup-host.sh, which sets pi's
# defaultModel the same way, so mu and pi resolve to the same local model without
# either repo depending on the other. Keep the two in sync if you change them.
#
# Idempotent: re-run after a GPU change and it rewrites ~/.zshrc.mu.
set -euo pipefail

ZSHRC_MU="$HOME/.zshrc.mu"

# ── Detect GPU VRAM (NVIDIA only; Macs use unified memory → conservative default) ─
nvidia_vram_mib() {
    command -v nvidia-smi > /dev/null 2>&1 || return 1
    nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null \
      | head -n1 | tr -dc '0-9'
}
nvidia_name() {
    nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -n1
}

VRAM_MIB=""
GPU_DESC="none detected (using unified-memory / conservative default)"
if [ "$(uname -s)" = "Linux" ]; then
    VRAM_MIB="$(nvidia_vram_mib || true)"
    [ -n "${VRAM_MIB:-}" ] && GPU_DESC="$(nvidia_name) — ${VRAM_MIB} MiB VRAM"
fi

# ── Pick a hardware profile ───────────────────────────────────────────────────
# A discrete NVIDIA card with ≥6 GB has room for the larger Q4_K_M weights plus a
# bigger KV cache (measured: 7B Q4_K_M at 12288 ctx loads fully on a 6 GB card,
# ~5.3/6.0 GB used). Everything else — Macs, Intel iGPUs, smaller/older cards —
# stays on the 3B / 6000 defaults mu already encodes.
if [ -n "${VRAM_MIB:-}" ] && [ "$VRAM_MIB" -ge 6000 ] 2>/dev/null; then
    PROFILE="roomy"
    NUM_CTX="12288"
    AGENT_MODEL="qwen2.5-coder-7b-instruct"   # capable card → the 7B
else
    PROFILE="default"
    NUM_CTX="6000"                            # mu's own MU_NUM_CTX default
    AGENT_MODEL="qwen2.5-coder-3b-instruct"   # conservative → snappier 3B
fi

echo "Host hardware profile"
echo "  GPU:            $GPU_DESC"
echo "  Profile:        $PROFILE"
echo "  MU_AGENT_MODEL: $AGENT_MODEL"
echo "  MU_NUM_CTX:     $NUM_CTX"
echo ""

# ── Write ~/.zshrc.mu ─────────────────────────────────────────────────────────
{
    echo "# ~/.zshrc.mu — generated by mu's scripts/setup-host.sh. Do not edit;"
    echo "# re-run 'make setup-host' to regenerate. Machine-local, outside the repo."
    echo "# Host: $(uname -n) | GPU: $GPU_DESC | profile: $PROFILE"
    echo ""
    echo "export MU_AGENT_MODEL=$AGENT_MODEL"
    [ "$NUM_CTX" != "6000" ] && echo "export MU_NUM_CTX=$NUM_CTX"
} > "$ZSHRC_MU"

if [ "$NUM_CTX" = "6000" ]; then
    echo "  ✓ Wrote $ZSHRC_MU (MU_AGENT_MODEL=$AGENT_MODEL; MU_NUM_CTX uses mu's 6000 default)"
else
    echo "  ✓ Wrote $ZSHRC_MU (MU_AGENT_MODEL=$AGENT_MODEL, MU_NUM_CTX=$NUM_CTX)"
fi
echo ""
echo "Done. Open a new shell, or 'source ~/.zshrc.mu' to apply now."
echo "If your shell rc doesn't already source it, add:"
echo '    [ -r "$HOME/.zshrc.mu" ] && source "$HOME/.zshrc.mu"'
